name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: config.settings.dev
  DJANGO_SECRET_KEY: django-secret-key-ci

jobs:

  local:
    runs-on: ubuntu-latest

    concurrency:
      group: ci-dev-${{ github.ref }}
      cancel-in-progress: true

    env:
      COMPOSE_FILE: ci/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: install system dependency
        run: bash scripts/install-google-chrome.sh

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: poc-django
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Create environment variables file
        run: |
          export GID=$(id -g)
          envsubst < .env.tpl > .env-base
          grep -v "=$" .env-base > .env
          rm .env-base

      - name: install
        run: poetry install

      - name: test
        run: pytest

      - name: Run pre-commit check
        run: |
          pre-commit install
          pre-commit run --all-files

  docker:
    runs-on: ubuntu-latest

    concurrency:
      group: ci-dev-${{ github.ref }}
      cancel-in-progress: true

    env:
      COMPOSE_FILE: ci/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: poc-django
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Create environment variables file
        run: |
          export GID=$(id -g)
          envsubst < .env.tpl > .env-base
          grep -v "=$" .env-base > .env
          rm .env-base

      - name: Build djangopoc image
        run: make docker-build

      - name: start services
        run: |
          make docker-start

      # skip for now: sqlite3.OperationalError: unable to open database file
      # - name: waiting for services
      #   run: |
      #     make docker-wait

      - name: docker log
        if: ${{ failure() }}
        run: make docker-logs SERVICE=django
